server:
  port: 17000
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chkprivate?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true&useSSL=false
      username: root
      password: root

