server:
  port: 17000
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chkprivate?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true&useSSL=false
      username: root
      password: root
#spring:
#  datasource:
#    druid:
#      initialSize: 5
#      maxActive: 85
#      maxWait: 20
#      stat-view-servlet:
#        login-username: chk
#        login-password: root
#      web-stat-filter:
#        enable: true
#        url-pattern: */